server:
  port: 8601
spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: informationLayer
  #################################redis配置########################################
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 10000 # 连接超时时间（毫秒）
    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）默认 -1
        max-idle: 8 # 连接池中的最大空闲连接默认 8
        min-idle: 0 # 连接池中的最小空闲连接默认 0
  #################################redis配置########################################
  #####################################################################################################
  # mysql 属性配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://zzdnjs.mysql.polardb.rds.aliyuncs.com:3306/zydj?useSSL=false
    #    username: zydj
    #    password: Zydj123456!@#
    #    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.117.150:3306/zydj?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
    username: dangjian
    password: Ahtr924!!
  #    url: jdbc:mysql://localhost:3306/zydj?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
  #    username: root
  #    password: root

  #  jpa:
  #    hibernate:
  #      #ddl-auto: create #ddl-auto:设为create表示每次都重新建表
  #      ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
  #    show-sql: true
  #####################################################################################################

  #####################################################################################################
  # mybatis mapper xml 配置
  #mybatis:
  # mybatis.type-aliases-package：指定domain类的基包，即指定其在*Mapper.xml文件中可以使用简名来代替全类名（看后边的UserMapper.xml介绍）
  #type-aliases-package:
  #mapper-locations: classpath:mybatis/mapper/*.xml
  #config-location: classpath:mybatis/mybatis-config.xml

# mybatis-plus 配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.zznode.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    # 热加载mapper文件
    refresh: true
    db-config:
      db-type: mysql
#####################################################################################################
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://localhost:8001/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka serverå
    prefer-ip-address: true
logging:
  level:
    org.zznode: DEBUG
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.authorize: DEBUG

prov:
  limit: 2

cron:
  updatescore: 0 0 1 * * ?
  sensitiveCron: 0 0 */10 * * ?